### ISSUE TITLE
std::load 

### ISSUE THREAD

**Issue by nolem321** [InvenireAude/IAS-Base-OSS#1]
When I try to load a not existing file I'm  getting exception:
IASE-2004 Rollback: RollbackMeException Program error: InterpreterException: Exception 'XMLHelperException' :Cannot open: test/5F3132362F2B3A3D64.xml

How can I catch or prevent this exception. Is there something like std::fileExist?
I'm tying catch Exception : "http://www.invenireaude.org/lang/workers"  
I must handle this exception and return error information in response.

**Comment by InvenireAudeAdmin** [comment]
1) Changed, the following instance will thrown:

```
<Exception xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://www.invenireaude.org/lang/builtin" xsi:type="ns0:Exception" name="ItemNotFoundException">
 <info>input</info>
</Exception>
```

2) We recomend using the defined IAS input/outputs wherever possible as the std::save & load methods are for debugging purposes mostly. E.g.:
```

IMPORT std::default;
IMPORT std::qs;

PROGRAM testloadnofile(
	VAR ctx   AS Context  : "http://www.invenireaude.org/qsystem/workers",
	VAR data  AS AnyType
)
BEGIN
	
	TRY BEGIN
	 data = std::receive("input",ctx); 
	END CATCH(VAR e AS AnyType) BEGIN
	 std::save("stdout", e);
	END;
	
END;

```
`ias_qs_processor -i file:/tmp/aaaa  -l run testloadnofile`
